# -*- coding: utf-8 -*-
"""Testes_de_Integração.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18wNQ1kuXO1ZqzY8kYMvn1odCfDpPOYUd
"""

import unittest
from app import login, home

class TestFluxoLogin(unittest.TestCase):
    def test_fluxo_login_completo(self):
        # Testa o fluxo completo de login e redirecionamento para a home
        usuario = "usuario_teste"
        senha = "senha_teste"
        login_resultado = login(usuario, senha)
        self.assertEqual(login_resultado, "Login bem-sucedido")

        # Verifica se, após o login, a tela inicial da home é carregada
        home_resultado = home()
        self.assertEqual(home_resultado, "Tela inicial da home carregada")

if __name__ == '__main__':
    unittest.main()

# Aqui, testei o fluxo de login e a navegação até a tela inicial (home).
# Primeiro, o login ocorre com sucesso e depois validamos se a home é
# carregada corretamente, simulando um fluxo real do app.

import unittest
from app import ir_para_home, ir_para_receitas, ir_para_detalhes_receita

class TestFluxoNavegacao(unittest.TestCase):
    def test_fluxo_completo_navegacao(self):
        # Primeiro, verificamos se a home é carregada
        home_resultado = ir_para_home()
        self.assertEqual(home_resultado, "Tela inicial da home carregada")

        # Em seguida, testamos a navegação até a página de receitas
        receitas_resultado = ir_para_receitas()
        self.assertEqual(receitas_resultado, "Página de receitas carregada com sucesso")

        # Por fim, testamos a navegação até a página de detalhes da receita
        detalhes_resultado = ir_para_detalhes_receita()
        self.assertEqual(detalhes_resultado, "Página de detalhes da receita carregada")

if __name__ == '__main__':
    unittest.main()


# Nesse teste, simulei a navegação entre várias telas. O fluxo começa com a home,
# vai para a página de receitas e depois para os detalhes de uma receita específica.
# Isso garante que a navegação entre as telas está funcionando conforme o esperado.